# Generated by Django 2.2.5 on 2020-07-11 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20200711_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
